'''A tool for generating the python code for a new agent.
'''
from __future__ import annotations


AGENT_DEFINITIONS = {
    "research_agent": '''
research_agent = Agent(
    name="research_agent",
    model="gemini-1.5-flash",
    instruction="You are a specialized research agent. Your purpose is to gather and analyze information from various sources, including the web. You should provide well-structured and relevant information to the coordinating agent.",
    description="Gathers and analyzes information.",
    tools=[google_search],
)
''',
    "reasoning_agent": '''
reasoning_agent = Agent(
    name="reasoning_agent",
    model="gemini-1.5-flash",
    instruction="You are a specialized reasoning agent. Your purpose is to perform logical deductions, solve problems, and make decisions based on the information provided. You should explain your reasoning process clearly.",
    description="Focuses on logical processing and decision-making.",
)
''',
    "creative_agent": '''
creative_agent = Agent(
    name="creative_agent",
    model="gemini-1.5-flash",
    instruction="You are a specialized creative agent. Your purpose is to generate novel ideas, create artistic content, and provide innovative solutions. Let your imagination run wild.",
    description="Handles tasks that require creativity and innovation.",
)
''',
    "memory_agent": '''
memory_agent = Agent(
    name="memory_agent",
    model="gemini-1.5-flash",
    instruction="You are a specialized memory agent. Your purpose is to manage the storage and retrieval of information. You will be asked to store information or recall previously stored information.",
    description="Manages the storage and retrieval of information.",
)
''',
    "planning_agent": '''
planning_agent = Agent(
    name="planning_agent",
    model="gemini-1.5-flash",
    instruction="You are a specialized planning agent. Your purpose is to create step-by-step plans to achieve a goal. You should break down complex tasks into smaller, manageable steps.",
    description="Involved in strategizing and organizing tasks.",
)
''',
    "execution_agent": '''
execution_agent = Agent(
    name="execution_agent",
    model="gemini-1.5-flash",
    instruction="You are a specialized execution agent. Your purpose is to carry out tasks as defined by the planning agent. You have access to tools to interact with the environment.",
    description="Carries out planned actions and tasks.",
)
''',
    "evaluation_agent": '''
evaluation_agent = Agent(
    name="evaluation_agent",
    model="gemini-1.5-flash",
    instruction="You are a specialized evaluation agent. Your purpose is to assess the outcome and performance of tasks. You should provide a critical evaluation and suggest improvements.",
    description="Assesses the outcomes and performance of tasks.",
)
''',
}

def generate_agent_code(
    root_agent_name: str,
    root_agent_instruction: str,
    root_agent_description: str,
    sub_agents: list[str],
) -> str:
    """Generates the Python code for a new agent.py file.

    Args:
        root_agent_name: The name for the new root agent.
        root_agent_instruction: The instruction for the new root agent.
        root_agent_description: The description for the new root agent.
        sub_agents: A list of specialized agent names to include as sub_agents.

    Returns:
        A string containing the complete Python code for the agent.py file.
    """
    imports = [
        "from __future__ import annotations",
        "from google.adk.agents import Agent",
    ]
    has_search = "research_agent" in sub_agents
    if has_search:
        imports.append("from google.adk.tools import google_search")

    sub_agent_definitions = []
    for agent_name in sub_agents:
        if agent_name in AGENT_DEFINITIONS:
            sub_agent_definitions.append(AGENT_DEFINITIONS[agent_name])

    root_agent_definition = f"""
root_agent = Agent(
    name=\"{root_agent_name}\",
    model=\"gemini-1.5-flash\",
    instruction='''{root_agent_instruction}''',
    description='''{root_agent_description}''',
    sub_agents=[
        {', '.join(sub_agents)}
    ],
)
"""

    return "\n\n".join(
        [
            "'''This file was generated by the Nexus Agent Builder.'''",
            "\n".join(imports),
            *sub_agent_definitions,
            root_agent_definition,
        ]
    )
